### ISSUE TITLE
Dynamic modules

### ISSUE THREAD

**Issue by pando85** [rash-sh/rash#151]
Create new modules written in Rash.

This modules will need at least some metadata and a function to execute.

metadata schema:
```
name:
  type: string
params:
  type: object
  additional_properties:
    type:
      - string
      - number
      - object
      - array
      - boolean
 ```

Function definition:
- SHOULD verify params.
- MUST do the job.
- MUST return if something changed (boolean).
- COULD return some output or extra.
