### ISSUE TITLE
handlers

### ISSUE THREAD

**Issue by pando85** [rash-sh/rash#222]
https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html

- Add notify to Tasks.
- Add handlers:
  - Other file (e.g. `{{name}}.handlers.rh`)?
  - Include handlers task (`include_handlers`)?
  - Task param to register handlers?:
  ```yaml
  - name: Register all handlers
    handlers:
    - name: enable buu
      service:
        name: buu
        state: enabled
  ```
  - As boolean attr in task: `is_handler: true`?
- Add `meta: flush_handlers`
