### ISSUE TITLE
Symbolic Links

### ISSUE THREAD

**Issue by theowenyoung** [rash-sh/rash#257]
**Is your feature request related to a problem? Please describe.**

Yes, I want to use rash to manage my dotfiles, I need to create symbolic links for some files, but it seems there are no simple way to do it.

**Describe the solution you'd like**

Maybe like this:

```yaml
link:
  src: ./src
  dest: ./dest
```

**Describe alternatives you've considered**

use command

**Additional context**
Add any other context about the feature request here.

**Comment by pando85** [comment]
Hello @theowenyoung,
This has to be implemented in the [`file` module](https://github.com/rash-sh/rash/blob/99c2399b60192da95fe0d910ad933ae886aef1a6/rash_core/src/modules/file.rs#L182).
I dunno if I would have time to do it. I would like to make your project viable. Anyhow, do you know Rust? (just to know).

For my dotfiles I would like to upload the project to a public repo and add it to the documentation and examples but in the meanwhile... I'm using this if it is useful for you:
```
 #!/usr/bin/env -S rash --diff
#
# dots easy manage of your dotfiles.
# Usage:
#   ./dots (install|update|help) <package_filters>...
#
# Arguments:
#   package_filters   List of regex matching packages wanted.
#
# Options:
#   -c,--check  dry-run mode
#
# Example:
#   ./dots install --check '.*zsh.*'
#
# Subcommands:
#   install      Copy files to host.
#   update    Get files from host.
#   help         Show this screen.
#
- name: set vars
  set_vars:
    dotfiles_dir: "{{ rash.dir }}/dotfiles"

- name: find dotfiles to copy
  find:
    paths: "{{ dotfiles_dir }}"
    hidden: true
    patterns: "{{ package_filters | default(value=omit()) | json_encode() }}"
    recurse: true
  changed_when: false
  register: dotfiles

- name: find dotfiles directories to create structure
  find:
    paths: "{{ dotfiles_dir }}"
    hidden: true
    recurse: true
    excludes: dotfiles
    file_type: directory
  changed_when: false
  register: dotfiles_dirs

- name: create dotfiles directories
  file:
    path: "{{ item | replace(from=dotfiles_dir, to=env.HOME) }}"
    state: "directory"
  loop: "{{ dotfiles_dirs.extra }}"
  when: install

- name: copy dotfiles
  copy:
    src: "{{ item }}"
    dest: "{{ item | replace(from=dotfiles_dir, to=env.HOME) }}"
    mode: preserve
  loop: "{{ dotfiles.extra }}"
  when: install

- name: update dotfiles
  copy:
    src: "{{ item | replace(from=dotfiles_dir, to=env.HOME) }}"
    dest: "{{ item }}"
    mode: preserve
  loop: "{{ dotfiles.extra }}"
  when: update
```
