### ISSUE TITLE
[NEW]Allow set vars with other data structures , like array

### ISSUE THREAD

**Issue by theowenyoung** [rash-sh/rash#258]
**Is your feature request related to a problem? Please describe.**

hi, I have a couple of files need to copy to another place, I want't use `loop` function,

```yaml
command: "echo {{item.name}}"
loop:
  - ["test1","test2"]
  - ["test3","test4]
```

Another case:

```yaml
setvars:
  test:
      property1: [1,2,3]

```

**Comment by theowenyoung** [comment]
> Anyway, I don't get the loop proposal that you wrote there. How is that supposed to work?

ohoh, it's a wrong example, correct it:

```yaml
command: "echo {{item[0]}} {{item[1]}}"
loop:
  - ["test1","test2"]
  - ["test3","test4]
```
