### ISSUE TITLE
Docopt option parse ignored

### ISSUE THREAD

**Issue by pando85** [rash-sh/rash#279]
**Describe the bug**
In command line interface when you pass an option if one argument is expected is caught as argument and ignored.

**To Reproduce**
E.g. `test.rh`:
```yaml
#!/usr/bin/env -S rash --
#
# Test
#
# Usage:
#   ./test.rh [--help] <foo>

- debug:
    msg: boo
```

```
./test.rh --help
```

**Expected behavior**
Print help
```
Test

Usage:
  ./test.rh [--help] <foo>
Note: Options must be preceded by `--`. If not you are passing options directly to rash.
For more information check rash options with `rash --help`.
```

**Command output**
```
TASK [debug] - 1 to go - *******************************************************************
ok: boo
```
