### ISSUE TITLE
Duplicated option docopt is parsed as boolean

### ISSUE THREAD

**Issue by pando85** [rash-sh/rash#280]
**Describe the bug**
When you define a option that can be repeated it is parsed as a boolean in the docopt args parser.

**To Reproduce**
With this script as `/tm/test.rh`
```yaml#!/bin/rash
#
# Test
#
# Usage:
#   ./test.rh [--help]
#   ./test.rh [-d]...

- name: Print args
  debug:
    var: __tera_context
```
```bash
 /tmp/test.rh -- -dd | grep -A3 options
```

**Expected behavior**

```bash
  "options": {
    "d": 2,
    "help": false
  }
```

**Command output**
```
  "options": {
    "d": true,
    "help": false
  }
```
