### ISSUE TITLE
copy: [ERROR] stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by pando85** [rash-sh/rash#461]
**Describe the bug**
Error is generated when copy non valid UTF-8 files.

**To Reproduce**
```
- copy:
    src: file.jpg
    dest: /tmp/file.jpg
    mode: preserve
```

**Expected behavior**
Copy the file to the desired location.

**Command output**
```
[ERROR] stream did not contain valid UTF-8
```
