### ISSUE TITLE
when support list

### ISSUE THREAD

**Issue by pando85** [rash-sh/rash#72]
Add support for lists in `when`.

```yaml
- command: echo "hello"
  when:
    - 1 == 1
    - foo == "boo"
```
