### ISSUE TITLE
[ERROR] undefined value (in t:1)

### ISSUE THREAD

**Issue by yonas** [rash-sh/rash#766]
**Describe the bug**
Getting `[ERROR] undefined value (in t:1)` when copying a file with a template variable.

**To Reproduce**
`config.j2`

```j2
Log level is: {{ log_level }}
```

`setup.rh`
```yaml
#!/usr/bin/env rash

- name: Verify input parameters
  assert:
    that:
      - env.LOG_LEVEL is defined

- name: Configure application
  vars:
    log_level: "{{ env.LOG_LEVEL | default('INFO') }}"
  template:
    src: config.j2
    dest: /tmp/config.json
    mode: "0600"
```

**Expected behavior**
`cat /tmp/config.json` should show `Log level is: DEBUG`

**Command output**
```sh
$ LOG_LEVEL=DEBUG rash -v setup.rh
TASK [/usr/local/etc/nsd/features/setup.rh:Verify input parameters] - 2 to go - ******************************************************************************************************************************
Module: assert
Params: Mapping {"that": Sequence [String("env.LOG_LEVEL is defined")]}
ok
TASK [/usr/local/etc/nsd/features/setup.rh:Configure application] - 1 to go - ********************************************************************************************************************************
Module: template
Params: Mapping {"src": String("config.j2"), "dest": String("/tmp/config.json"), "mode": String("0600")}
[ERROR] undefined value (in t:1)
```

**Additional context**
v2.9.11
FreeBSD 14
