### ISSUE TITLE
[ feature request ] Support data file (minijinja template context)

### ISSUE THREAD

**Issue by yonas** [rash-sh/rash#769]
**Is your feature request related to a problem? Please describe.**
I'd like to supply a file containing variables to be used when copying template files.

**Describe the solution you'd like**
minijinja has the ability to obtain variables from the following file formats: `auto, cbor, ini, json, querystring, toml, yaml`.

I'd like to do something like:

```yaml

- name: Verify input parameters
  assert:
    that:
      - env.VARS_FILE is defined

- name: Configure application
  include_vars: "{{ env.VARS_FILE  }}"
  template:
    src: config.j2
    dest: /tmp/config.json
    mode: "0600"
```

**Describe alternatives you've considered**
n/a
