### ISSUE TITLE
Support for block statements 

### ISSUE THREAD

**Issue by pando85** [rash-sh/rash#777]
### Summary
Introduce a new `block` directive in Rash that functions similarly to Ansible’s blocks. This directive will let users group tasks, handle errors with a `rescue` section, and run cleanup steps in an `always` section. Blocks should be nestable to allow complex workflows.

---

### Requirements

1. **Block Syntax**  
   - A top-level `block` directive containing one or more tasks or sub-blocks.  
   - Nested blocks must be supported for advanced logic and multiple levels of error handling.

2. **Error Management**  
   - A `rescue` section that runs if any task within the block fails.  
   - An `always` section that runs unconditionally at the end of the block.

3. **Directive & Modules**  
   - This directive should function as standard Rash code, allowing any existing tasks or modules (such as `pacman`, `copy`, or `command`) to be placed within a block or nested block.  
   - Ensure the directive can be nested multiple levels deep, providing flexible flow control within Rash.

4. **Conditional Execution**  
   - Enable optional conditions on entire blocks or on individual tasks, maintaining consistency with Rash’s existing conditional syntax.

5. **Documentation & Testing**  
   - Deliver comprehensive documentation with examples and best practices.  
   - Include tests covering normal, error, and nested-block scenarios.

---

### Example
```yaml
- name: Demonstrate block directive in Rash
  block:
    - name: Gather system info
      debug:
        msg: "OS Version: {{ rash.system.version }}"

    - name: Install required packages
      pacman:
        name: "my_package"
        state: latest

    - name: Nested block example
      block:
        - name: Create a file
          copy:
            src: "./somefile.txt"
            dest: "/tmp/somefile.txt"

        always:
          - name: Nested block cleanup
            command:
              cmd: "rm -f /tmp/somefile.txt"

  rescue:
    - name: Handle errors
      debug:
        msg: "Installation or file creation failed. Rolling back."

  always:
    - name: Final cleanup
      command:
        cmd: "rm -rf /tmp/*.tmp"
```
