### ISSUE TITLE
command + register: remove '\n' from registered var output

### ISSUE THREAD

**Issue by sdelrio** [rash-sh/rash#91]
```
 - name: "resolve to ip address" 
    command: |
      getent hosts {{ env.HS110IP }} |
      cut -f1 -d' '                                                                                                                                                                                               
    register: ipaddress         
 - name: "my command execution"
    command:  my app -ip {{ ipaddress.output }} -p2 parameter2 -p3 parameter 3
```

Then I enter my container and if found the process runinng with just the first parameter, and I found this is because there is a `\n` at the end of `ipaddress.output`.

The fix I am doing now is removing the `\n` with `tr` like this:
```
 - name: "resolve to ip address" 
    command: |
      getent hosts {{ env.HS110IP }} |
      cut -f1 -d' ' | tr -d "\n"                                                                                                                                                                                                  
    register: ipaddress         
```

**Comment by pando85** [comment]
Output contains full output without trimming and I think this is correct.

I think that your approach right now it is correct. For me, if I'm using echo to store values in output I have to use `echo -n` too.

Trimming output could be tricky because it is not expected behaviour and register is not the main purpose of output field.

**Comment by sdelrio** [comment]
Fixed with Tera functions so I don't have to depend on external cut, sed, etc... , I leave the code here, if it can help.

```
- name: "CONFIG | resolve IP address"
  command: getent hosts {{ env.IP }}
  register: getent_result

- name: "CONFIG | Get IP address"
  set_vars:
    ipaddress: "{{ getent_result.output | replace(from='\n', to='') | split(pat=' ') | first | trim }}"
```
